#!/usr/bin/env python3
"""Scaffold a new platform: ``make new-platform id=<platform_id>``.

Creates
  platforms/<id>/platform.yaml, ardupilot.parm, meshes/README.md   (from platforms/_template)
  sim/Plugins/CDSimPlatform_<id>/                                  (UE5 plugin skeleton)
then validates the new manifest. Refuses to overwrite anything.
Spec: docs/04_PLATFORM_PLUGIN_SPEC.md
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

from cdsim_common.manifests import ManifestError, ManifestKind, validate_file
from cdsim_common.paths import repo_root

ID_RE = re.compile(r"^[a-z][a-z0-9_]{2,40}$")

UPLUGIN = """{{
\t"FileVersion": 3,
\t"Version": 1,
\t"VersionName": "0.1.0",
\t"FriendlyName": "CD Sim Platform: {name}",
\t"Description": "Platform plugin for {pid}. Data: platforms/{pid}/platform.yaml",
\t"Category": "CD Sim Platforms",
\t"CreatedBy": "Chakravyuha Dynamics Private Limited",
\t"CanContainContent": true,
\t"Installed": false,
\t"Modules": [
\t\t{{
\t\t\t"Name": "{plugin}",
\t\t\t"Type": "Runtime",
\t\t\t"LoadingPhase": "Default"
\t\t}}
\t],
\t"Plugins": []
}}
"""

BUILD_CS = """// Copyright (c) 2026 Chakravyuha Dynamics Private Limited. Proprietary and confidential.
// UNVERIFIED BUILD — generated by scripts/new_platform.py; see docs/BUILDING_UE5.md

using UnrealBuildTool;

public class {plugin} : ModuleRules
{{
\tpublic {plugin}(ReadOnlyTargetRules Target) : base(Target)
\t{{
\t\tPCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
\t\tPublicDependencyModuleNames.AddRange(new string[] {{ "Core", "CoreUObject", "Engine", "CDSim" }});
\t}}
}}
"""

MODULE_H = """// Copyright (c) 2026 Chakravyuha Dynamics Private Limited. Proprietary and confidential.
// UNVERIFIED BUILD — generated by scripts/new_platform.py; see docs/BUILDING_UE5.md

#pragma once

#include "Modules/ModuleManager.h"

/** Platform plugin for '{pid}'. Vehicle behaviour comes from platforms/{pid}/platform.yaml;
 *  this module only contributes assets (meshes, materials, sockets) and optional
 *  platform-specific components. The core must never need edits for a new platform. */
class F{plugin}Module : public IModuleInterface
{{
public:
\tvirtual void StartupModule() override;
\tvirtual void ShutdownModule() override;
}};
"""

MODULE_CPP = """// Copyright (c) 2026 Chakravyuha Dynamics Private Limited. Proprietary and confidential.
// UNVERIFIED BUILD — generated by scripts/new_platform.py; see docs/BUILDING_UE5.md

#include "{plugin}.h"

IMPLEMENT_MODULE(F{plugin}Module, {plugin})

void F{plugin}Module::StartupModule()
{{
\t// TODO: register platform-specific components/assets for '{pid}' if needed.
}}

void F{plugin}Module::ShutdownModule()
{{
}}
"""


def main(argv: list[str]) -> int:
    if len(argv) != 1 or not ID_RE.match(argv[0]):
        print("usage: new_platform.py <id>  (lowercase, digits, underscores; 3-41 chars)")
        return 2
    pid = argv[0]
    root = repo_root(Path(__file__))
    assert root is not None
    pdir = root / "platforms" / pid
    plugin = f"CDSimPlatform_{pid}"
    udir = root / "sim" / "Plugins" / plugin
    for d in (pdir, udir):
        if d.exists():
            print(f"refusing to overwrite existing {d.relative_to(root)}")
            return 1

    name = pid.replace("_", " ").title()
    shutil.copytree(root / "platforms" / "_template", pdir)
    for f in pdir.rglob("*"):
        if f.is_file():
            text = f.read_text(encoding="utf-8")
            f.write_text(
                text.replace("__PLATFORM_ID__", pid).replace("__PLATFORM_NAME__", name),
                encoding="utf-8",
            )
    (pdir / "meshes").mkdir(exist_ok=True)
    (pdir / "meshes" / "README.md").write_text(
        f"# {pid} — meshes\n\nPlace CAD (STEP) and exported FBX here (Git LFS). "
        "See docs/04_PLATFORM_PLUGIN_SPEC.md §\"Swapping in real CAD\".\n",
        encoding="utf-8",
    )

    src = udir / "Source" / plugin
    (src).mkdir(parents=True)
    (udir / "Content").mkdir()
    (udir / "Content" / "README.md").write_text(
        f"Assets for {pid} (Git LFS). Empty until geometry is supplied.\n", encoding="utf-8"
    )
    fmt = {"pid": pid, "plugin": plugin, "name": name}
    (udir / f"{plugin}.uplugin").write_text(UPLUGIN.format(**fmt), encoding="utf-8")
    (src / f"{plugin}.Build.cs").write_text(BUILD_CS.format(**fmt), encoding="utf-8")
    (src / f"{plugin}.h").write_text(MODULE_H.format(**fmt), encoding="utf-8")
    (src / f"{plugin}.cpp").write_text(MODULE_CPP.format(**fmt), encoding="utf-8")

    schemas = root / "schemas" / "json"
    try:
        validate_file(pdir / "platform.yaml", ManifestKind.PLATFORM, schemas)
    except ManifestError as exc:
        print(f"scaffold created but invalid (template bug): {exc}")
        return 1
    print(f"created platforms/{pid}/ and sim/Plugins/{plugin}/")
    print("next: edit platform.yaml + ardupilot.parm, add the plugin to sim/CDSim.uproject,")
    print("      run `make schemas`, then follow docs/04_PLATFORM_PLUGIN_SPEC.md")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
