#!/usr/bin/env bash
# Generates ditto/nginx/nginx.htpasswd from DITTO_USER / DITTO_PASSWORD in .env (git-ignored).
# Extra service users (analytics, maintenance) are added in later phases via the same mechanism.
. "$(dirname "$0")/common.sh"
OUT=ditto/nginx/nginx.htpasswd
hash_pw() {
  if command -v openssl >/dev/null 2>&1; then openssl passwd -apr1 "$1";
  else printf '{PLAIN}%s' "$1"; fi
}
{
  echo "# generated by scripts/gen-htpasswd.sh - do not commit"
  echo "${DITTO_USER}:$(hash_pw "${DITTO_PASSWORD}")"
  for svc in analytics maintenance; do
    var="$(echo "$svc" | tr a-z A-Z)_DITTO_PASSWORD"
    if [ -n "${!var:-}" ]; then echo "${svc}:$(hash_pw "${!var}")"; fi
  done
} > "$OUT"
log "wrote $OUT ($(grep -vc '^#' "$OUT") user(s))"
